### ISSUE TITLE
reviewapps/ignore ラベルを持つPRが2個あるとエラーになる（かもしれない）

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/reviewapp-operator#85]
PRが3つあり、そのうち2つが `reviewapps/ignore` ラベルを持っているとき以下のエラーでクラッシュしている。1つからラベルを消すと発生しなくなった。

```
2022-02-13T01:32:21.474Z        INFO    controllers.ReviewApp   fetching ReviewApp resource: reviewapp-operator-system/dreamkast-dk-cloudnativedaysjp-dreamkast-1151
2022-02-13T01:32:21.474Z        INFO    controllers.ReviewAppManager    fetching ReviewAppManager resource: reviewapp-operator-system/dreamkast-dk
panic: runtime error: slice bounds out of range [3:2]

goroutine 315 [running]:
github.com/cloudnativedaysjp/reviewapp-operator/services.(*GitRemoteRepoAppService).ListOpenPullRequestWithSpecificConditions.func1(...)
        /workspace/services/git_remoterepo_app.go:35
github.com/cloudnativedaysjp/reviewapp-operator/services.(*GitRemoteRepoAppService).ListOpenPullRequestWithSpecificConditions(0xc00083fb20, 0x2517cd8, 0xc000831410, 0xc00092c858, 0x11, 0xc000933930, 0x9, 0xc00092c870, 0x16, 0xc00081c720, ...)
        /workspace/services/git_remoterepo_app.go:44 +0x7ff
github.com/cloudnativedaysjp/reviewapp-operator/controllers.(*ReviewAppManagerReconciler).reconcile(0xc0006fe680, 0x2517cd8, 0xc000831410, 0xc00059ea00, 0xc000057f00, 0x19, 0xc0009338a0, 0xc)
        /workspace/controllers/reviewappmanager_controller.go:85 +0x36e
github.com/cloudnativedaysjp/reviewapp-operator/controllers.(*ReviewAppManagerReconciler).Reconcile(0xc0006fe680, 0x2517cd8, 0xc000831410, 0xc000057f00, 0x19, 0xc0009338a0, 0xc, 0xc000831410, 0xc000831380, 0xc000aa1db0, ...)
        /workspace/controllers/reviewappmanager_controller.go:68 +0x3ae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000450c80, 0x2517cd8, 0xc000831380, 0xc000057f00, 0x19, 0xc0009338a0, 0xc, 0xc000831300, 0x0, 0x0, ...)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:114 +0x247
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000450c80, 0x2517c30, 0xc0008b5240, 0x1fe3b60, 0xc000a8e9c0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:311 +0x305
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000450c80, 0x2517c30, 0xc0008b5240, 0x0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0009321b0, 0xc000450c80, 0x2517c30, 0xc0008b5240)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:223 +0x425
```

**Comment by ShotaKitazawa** [comment]
#86 で修正済み
